In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px

from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
import pickle

with open('../../bases/credit.pkl', 'rb') as f:
    X_credit_treinamento, Y_credit_treinamento, X_credit_teste, Y_credit_teste = pickle.load(f)

In [3]:
X_credit = np.concatenate((X_credit_treinamento, X_credit_teste), axis = 0)
Y_credit = np.concatenate((Y_credit_treinamento, Y_credit_teste), axis = 0)

In [4]:
classificador_rede_neural = MLPClassifier(activation='relu', batch_size=56, solver='adam')
classificador_rede_neural.fit(X_credit, Y_credit)

C:\Users\mathe\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\neural_network\_multilayer_perceptron.py:702: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier(batch_size=56)

In [5]:
classificador_arvore = DecisionTreeClassifier(criterion='entropy', min_samples_leaf=1, min_samples_split=5, splitter='best')
classificador_arvore.fit(X_credit, Y_credit)

DecisionTreeClassifier(criterion='entropy', min_samples_split=5)

In [6]:
classificador_svm = SVC(C = 2.0, kernel='rbf')
classificador_svm.fit(X_credit, Y_credit)

SVC(C=2.0)

In [7]:
classificador_rede_neural = MLPClassifier(activation='relu', batch_size=56, solver='adam')
classificador_rede_neural.fit(X_credit, Y_credit)

C:\Users\mathe\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\neural_network\_multilayer_perceptron.py:702: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier(batch_size=56)

In [8]:
pickle.dump(classificador_rede_neural, open('rede_neural_finalizado.sav', 'wb'))
pickle.dump(classificador_arvore, open('arvore_finalizado.sav', 'wb'))
pickle.dump(classificador_svm, open('svm_finalizado.sav', 'wb'))


In [9]:
rn = pickle.load(open('rede_neural_finalizado.sav', 'rb'))
arvore = pickle.load(open('arvore_finalizado.sav', 'rb'))
svm = pickle.load(open('svm_finalizado.sav', 'rb'))

In [68]:
registro = X_credit[500]

In [69]:
registro

array([ 0.83535389, -1.1487454 ,  2.02214244])

In [70]:
registro = registro.reshape(1, -1)

In [71]:
registro.shape

(1, 3)

In [72]:
rn.predict(registro)

array([1], dtype=int64)

In [73]:
arvore.predict(registro)

array([1], dtype=int64)

In [74]:
svm.predict(registro)

array([1], dtype=int64)